---
    wkhtmltopdf_url: http://iweb.dl.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
    php_ppa: php5-5.6
    doc_root: /vagrant/web
    sys_packages: [
        "git",
        "nodejs",
        "npm"
    ]
    php_packages: [
        "php5-cli",
        "php-pear",
        "php5-curl",
        "php5-intl",
        "php5-mcrypt",
        "php5-imagick",
        "php5-xdebug",
        "php5-mysql"
    ]
    php_ini_settings: [
        { reg: 'date.timezone =', line: 'date.timezone = {{ timezone }}' },
        { reg: 'max_execution_time =', line: 'max_execution_time = 0' },
        { reg: 'xdebug.max_nesting_level =', line: 'xdebug.max_nesting_level = {{ max_nesting_level }}' },
        { reg: 'memory_limit =', line: 'memory_limit = {{ memory_limit }}' },
        { reg: 'display_errors =', line: 'display_errors = true' },
        { reg: 'display_startup_errors =', line: 'display_startup_errors = true' },
        { reg: 'error_reporting =', line: 'error_reporting = E_ALL' },
        { reg: 'xdebug.remote_enable =', line: 'xdebug.remote_enable = 1' },
        { reg: 'xdebug.remote_handler =', line: 'xdebug.remote_handler = dbgp' },
        { reg: 'xdebug.remote_mode =', line: 'xdebug.remote_mode = req' },
        { reg: 'xdebug.remote_host =', line: 'xdebug.remote_host = {{ xdebug_ip }}' },
        { reg: 'xdebug.remote_port =', line: 'xdebug.remote_port = 9001' }
    ]
