---
    wkhtmltopdf_url: http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
    php_ppa: php5-5.6
    sys_packages: [
        "git",
        "nodejs",
        "npm",
        "graphviz"
    ]
    php_packages: [
        "php5-cli",
        "php5-gd",
        "php-pear",
        "php5-curl",
        "php5-intl",
        "php5-mcrypt",
        "php5-imagick",
        "php5-xdebug",
        "php5-mysql",
        "php5-sqlite",
        "phpunit"
    ]
    ws_vhost_path: /etc/apache2/sites-available
    ws_vhost_file: default
    ws_template: vhost.conf.tpl
    user: vagrant
    jackrabbit_ver: 2.10.1
    jackrabbit_port: 8080
    php_ini_settings: [
        { reg: 'date.timezone =', line: 'date.timezone = {{ timezone }}' },
        { reg: 'max_execution_time =', line: 'max_execution_time = 0' },
        { reg: 'xdebug.max_nesting_level =', line: 'xdebug.max_nesting_level = {{ max_nesting_level }}' },
        { reg: 'memory_limit =', line: 'memory_limit = 256M' },
        { reg: 'display_errors =', line: 'display_errors = false' },
        { reg: 'display_startup_errors =', line: 'display_startup_errors = false' },
        { reg: 'error_reporting =', line: 'error_reporting = E_ALL' },
        { reg: 'session.gc_maxlifetime =', line: 'session.gc_maxlifetime = 3600' }
    ]
