-   name: Install php7
    become: yes
    apt: pkg=php7.0 state=latest

#-   name: Setup php.ini
#    become: yes
#    lineinfile: dest="/etc/php/7.0/apache2/php.ini"
#                regexp="{{ item.reg }}"
#                line="{{ item.line }}"
#    with_items: php_ini_settings
    